spring.application.name=pokestore

# Demo app so token is not secure
arthur.app.jwtSecret=${JWT_SECRET}

#JWT Expiration
arthur.app.jwtExpirationMs=300000
# Refresh Token Expiration
arthur.app.jwtRefreshExpirationMs=604800000



# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://db:5432/pokestore_db
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true