spring.application.name=pokestore

# Demo app so token is not secure
arthur.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

#JWT Expiration
arthur.app.jwtExpirationMs=3600000
# Refresh Token Expiration
arthur.app.jwtRefreshExpirationMs=604800000

# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/pokestore_db
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true